import type { Metadata } from "next";
import { Libre_Baskerville, Sora } from "next/font/google";
import "./globals.scss";
import "@/scss/reset.css";
import "./_style.scss";

const sora = Sora({
  subsets: ["latin"],
  display: "swap",
});

const libreBaskerville = Libre_Baskerville({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sora.className} ${libreBaskerville.className}`}>
        <div className="content">{children}</div>
      </body>
    </html>
  );
}
